### ISSUE TITLE
多个终端消息记录不同步

### ISSUE THREAD

**Issue by liaojianqi** [redsx/NAMI#1]
多个终端消息记录不同步
（另，要是能多个设备同时登录就好了

**Comment by redsx** [comment]
已经实现了多端登录～
消息纪录不同步是什么？

**Comment by liaojianqi** [comment]
电脑端登录，发送消息A
手机端登录，发送消息B
电脑端登录，看不到消息B，没有在手机端发送的消息的那段聊天记录

不过可以多个终端登录就没有这个问题了。。。

**Comment by redsx** [comment]
你发送的消息可能是被系统过滤掉了
